### ISSUE TITLE
Adding VictimsFileDB to victims-lib-java

### ISSUE THREAD

**Issue by abn** [victims/victims-lib-java#10]
@victims/owners - Need consensus.  

Thinking of bringing in this implementation of (improved) into the lib.

https://github.com/victims/victims-client-java/blob/master/src/main/java/com/redhat/victims/VictimsFileDB.java

This essentially uses a cache directory that stores the database as follows:

```
+-- .victims-cache
    \+-- lastUpdated (file containing last sync time)
     |
     +-- db
         \-- sha512hash
            \+-- algorithm (file containing 1 entry per line)
             |
             +-- cves (file containing 1 cve per line)
```

**Comment by abn** [comment]
@gcmurphy @ashcrow  @dfj  thoughts?

**Comment by gcmurphy** [comment]
If you are simply wanting a cache why not just save the .json directly to the filesystem? The timestamp on the file could serve as the last updated date and the synchronization mechanism would only need to insert/remove information from the file as needed. For anything much more complicated or requiring queries then you probably should be using a database IMO.

**Comment by abn** [comment]
@gcmurphy  the idea is to provide a simple DB-like capability in the lib for when a database is not being used. So for any application building on this lib it has something to 'query' against.  Eg: the standalone client. Also we really do not want to store the entire response. We just need sha512s and cves. 

Dumping it as a json file will require a slightly complicated approach if I wanted to compare a scanned file to the available info. And this also provides for handling removes correctly too. And also finding a record would involve would require scanning all records. This way we can check by, _exists($CACHE/db/SHA512)_ and process file hashes only when required.

**Comment by gcmurphy** [comment]
That's fair enough I guess. Would it mean that you'd have to replicate the same functionality in the python and ruby libraries?

**Comment by abn** [comment]
Not necessarily, this is implemented for java clients only who might want to use this. Ideally the provides a reference Interface Implementation.

As for python clients, they can either use this functionality from the java-lib directly if required as we just want java hashing to be maintained by lib-java.

**Comment by abn** [comment]
This will no longer be done. Instead a simple jdbc:h2 based implementation will be added in #15 .
