### ISSUE TITLE
Add some logging capability

### ISSUE THREAD

**Issue by abn** [victims/victims-lib-java#14]

**Comment by abn** [comment]
@gcmurphy would this be better left to the client?

**Comment by gcmurphy** [comment]
In the case of victims-enforcer I have to use the maven logging capabilities i think. My instinct would be that if the library can't perform an operation it should return an error (or raise an exception). The client can base log messages from the error code / exception details.

**Comment by abn** [comment]
Agreed closing this as wontfix.

Raise a new issue if this is require at a later stage.
