### ISSUE TITLE
Add database impl

### ISSUE THREAD

**Issue by abn** [victims/victims-lib-java#15]

**Comment by abn** [comment]
Initial work started just using plain JDBC. Hibernate at this point would be a over-weight. 

A simple implementation is now ready. Will need to do a bit more testing. Embedded checks seems to no work as expected.

**Comment by abn** [comment]
Initial implementation done. @gcmurphy would be great if you can review that JDBC crap. :( 

https://github.com/victims/victims-lib-java/commit/6d8983a8624cf75b0ac8a631a28e13cd3708adf3

**Comment by abn** [comment]
An example usecase.

``` java
import java.io.IOException;

import com.google.gson.stream.MalformedJsonException;
import com.redhat.victims.database.VictimsDB;
import com.redhat.victims.database.VictimsDBInterface;

public class VTest {

    /**
     * @param args
     * @throws IOException 
     * @throws VictimsException 
     */
    public static void main(String[] args) throws IOException, VictimsException {
        VictimsDBInterface vdb = VictimsDB.db();
        try {
            vdb.synchronize();          
        } catch (VictimsException e) {
            if (e.getCause() instanceof MalformedJsonException){
                System.out.println("Server issue - Could not sync.");               
            }
        }
        for( VictimsRecord vr : VictimsScanner.getRecords(args[0])){
            for(String cve : vdb.getVulnerabilities(vr)){
                System.out.println(cve);
            }
        }
    }

}
```

**Comment by gcmurphy** [comment]
Looks reasonable. Although I'm not sure you are safely escaping the custom built query :trollface:. The other thing I noticed is that we aren't using the metadata at all. Is this something that will be added at a later stage or something I will have to tack on top of what you've already got there? Final question - does the subset matching still work the same way or have you made some improvements? I'll get started porting the victims-enforcer code to use this library and let you know if I hit any roadblocks. Hopefully this will make my life much easier :smile:.

**Comment by abn** [comment]
Yea the custom built query was just a quick workaround i figured we trust the input. But yes we should implement some escaping.

The properties matching will be implemented before release. I am thinking:

``` java
// Returns CVEs for all records that match all key/value given in properties
public ArrayList<String> getVulnerabilities(HashMap<String, String> properties);
```

Subset matching, the concept is still the same.
1. Count how many content hashes match per record
2. Count how many content hashes are present per per record
3. If the a record has counts in both equal, add its CVEs to list.

**Comment by gcmurphy** [comment]
:+1:  Ok sounds good.

**Comment by abn** [comment]
Added properties matching.
https://github.com/victims/victims-lib-java/commit/c8aaf6755fad4e6e8767da7b022cc2b5dd1cc872

**Comment by abn** [comment]
Disabled it on default e29901c

**Comment by abn** [comment]
Made te db configurable and stuff :) 

602c3b7

**Comment by abn** [comment]
Db implementation now complete. (Initial version at least).

**Comment by abn** [comment]
Escaping was introduced with https://github.com/victims/victims-lib-java/commit/5b67d177c602ae04ffb0afe82084b44dbfe83a97
