### ISSUE TITLE
Handle non-absolute paths in scanner

### ISSUE THREAD

**Issue by abn** [victims/victims-lib-java#27]
The VictimsScanner implementation does not handle paths like `~/path/to/file`.

**Comment by rnc** [comment]
Should it not also verify the path / file exists in scanSource?

**Comment by abn** [comment]
@rnc The test at https://github.com/victims/victims-lib-java/blob/6d90a3a471590f17177887a1833510e341d9bdb4/src/main/java/com/redhat/victims/VictimsScanner.java#L116 should handle that case.

**Comment by abn** [comment]
This has been fixed and will be available in next release.

**Comment by abn** [comment]
Change of mind, lib should not handle system specifics at the moment eg: `~/path`. 

Although, we normalize before use and that is it. Also now an invalid source will throw an IOException.
