### ISSUE TITLE
Implement Service class

### ISSUE THREAD

**Issue by abn** [victims/victims-lib-java#3]

**Comment by abn** [comment]
@gcmurphy  can you take a look at this see if something more is required for victims-enforcer?

**Comment by gcmurphy** [comment]
I think it might be better if the victims service was dynamic and received an InputStream rather than building the URI from hardcoded strings. For example this stops us having to deal with the SNI stuff and puts the onus on the consuming client. (see victims/victims-web/issues/22)

**Comment by abn** [comment]
The reason why i included to URI building here is to avoid any ambiguity  the consuming clients should only need to know it will receive a Victims record. The only thing that the consuming client should configure is the base url, the service entry point is coupled with the version of the data structure schema we implement in VictimsRecord. So I think it makes sense to make this non-configurable from the consumer. 

If the client might require sending input streams, it is always possible to refactor in such a way that this is possible too if required.

**Comment by abn** [comment]
Also note that RecordStream is an inner class designed to proved a yeildable object for a provided stream. With the ability to use a URI or an Input Stream (now). This is called by the VictimsService class which wraps the rest-api. This design provides for a standard mechanism across plugins maven, ant etc.

**Comment by gcmurphy** [comment]
Could this just be fixed by not using static invocation? As in you provide a default constructor for the VictimsService that uses the default URL's and provide another constructor that accepts a URL as a parameter? 

This would change it to something like: 

```
new VictimsService().updates(sdf.parse("01/01/2010"))
```

or 

```
new VictimsService("https://victi.ms/service").updates(sdf.parse("foo"))
```

It's probably not as nice though. Just an idea.

**Comment by abn** [comment]
@gcmurphy The more I thought about it having static method were a bad idea. Moved to be as described in your comment.

**Comment by gcmurphy** [comment]
lgtm
