### ISSUE TITLE
Check with OSS Team

### ISSUE THREAD

**Issue by abn** [victims/victims-lib-java#9]

**Comment by dfj** [comment]
Emailed OSAS, awaiting reply.

**Comment by abn** [comment]
@dfj last update i had was that we are sticking with com.redhat.victims.\* and no other changes. Is this accurate? Or is there something else to be considered?

**Comment by dfj** [comment]
OSAS suggested that we should move to ms.victi.\* or similar as a matter of correctness, but that there is no impediment to us using com.redhat.victims.*. Therefore I vote for leaving it for now.
